# ===================================================================
# KONFIGURASI KONEKSI DATABASE (PostgreSQL)
# ===================================================================
# Ganti [HOST_ANDA] dan [PASSWORD_ANDA].
# PENTING: Tambahkan ?sslmode=require di akhir URL untuk koneksi di cloud.
spring.datasource.url=jdbc:postgresql://db.vmhuizwmjgpilertgmjg.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=9E#bjjjQ_Q8u.zW

# Driver untuk PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# KONFIGURASI JPA & HIBERNATE
# ===================================================================
# Memberitahu Hibernate untuk menggunakan dialek PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Perintah ini akan secara otomatis memperbarui struktur tabel di database
# agar cocok dengan @Entity class Anda di Java. Sangat berguna untuk development.
spring.jpa.hibernate.ddl-auto=update
